package com.tms.common.enums;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    INVALID_TRANSITION,
    INVALID_CREDENTIALS,
    INVALID_FILE_TYPE,
    FILE_TOO_LARGE,
    ATTACHMENT_LIMIT_EXCEEDED
}
