spring:
  datasource:
    url: jdbc:h2:mem:tms;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
  h2:
    console:
      enabled: true

tms:
  attachments:
    storage-path: ${java.io.tmpdir}/tms-test-attachments
